### ISSUE TITLE
Need to have a better format for adding elements (especially devices/rooms) to the DB

### ISSUE THREAD

**Issue by xuther** [byuoitav/configuration-database-microservice#20]
Just had to add a device to the DB and it was a pain. We need to create some sort of a web form for doing this. (If not a web form, at the very least some stored procedures.)

**Comment by jessemillar** [comment]
I'm thinking we can make another "microservice" that's not meant to be deployed. We can use the Echo framework to serve up a UI using Go's templating engine and add entires to the database through that UI (when running the "microservice" locally). It'd basically be a script with a pretty UI that uses the frameworks we're already familiar with. Thoughts?

**Comment by jessemillar** [comment]
Being built here: https://github.com/byuoitav/configuration-database-tool
